### ISSUE TITLE
htmx?

### ISSUE THREAD

**Issue by guettli** [adamghill/django-unicorn#108]
Hi,

I was looking for a simple framework which helps me to build modern application with Django.

I had a look at several tools, but finally I will use htmx and Bootstrap5.

But maybe I missed something of django-unicorn.

Which benefits does django-unicorn give me, which I don't get from htmx and Bootstrap5?

**Comment by adamghill** [comment]
Hi, thanks for the great question and I should probably add a version of it to the documentation.

I've used `htmx` in the past to build sites and it is a great library to provide interactivity in your HTML. If you haven't looked at `alpine.js` that is another solid recommendation in the same "tier" as `htmx`, but approaches it in a slightly different way. For both of those libraries, what you get is a generalized front-end framework that you could use with any server-side framework (or just regular HTML). They are both well-supported, battle-tested, and answers to how they work are probably Google-able (or on Stackoverflow).

As far as I know, all of these libraries are a little bit different than Bootstrap which is primarily related to CSS and styling. The plugins provided by Bootstrap could probably be used with any of these libraries, although I haven't recently used it.

`Unicorn` isn't in the same league as either `htmx` or `alpine.js` (it hasn't been around as long, it isn't used as much, etc), but the benefit of `Unicorn` is that it is tightly integrated with Django and it should "feel" like an extension of the core Django experience. Just a few examples:
  - [redirecting](https://www.django-unicorn.com/docs/redirecting/#redirect) from an action just use the regular `redirect` shortcut
  - [validation](https://www.django-unicorn.com/docs/validation/#validation) uses Django forms just like you normally would
  - [Django Models](https://www.django-unicorn.com/docs/django-models/) are tightly integrated into `Unicorn` (especially if you look at the [$model](https://www.django-unicorn.com/docs/actions/#model) special argument)
  - you won't have to create extra URLs/views for AJAX calls to send back HTML because `Unicorn` handles all of that for you

But, you really can't go wrong with any choice you make. Good luck on your project!
