### ISSUE TITLE
Call function of a javascript module

### ISSUE THREAD

**Issue by nielsonsantana** [adamghill/django-unicorn#170]
First, I would like congrats for that awesome project and documentation. Nice job!
I'm trying use `django-unicorn` on a project and based on examples I guess that have many functions on JavaScript maybe cause conflicts.
There any possibility to call a javascript module function?
**Example:**
```javascript
  var Hellojs = (function() {
    var self = {};

    self.hello = function(name){
      alert("Hello " + name)
    }
    return self;
}());

  window.Hellojs = Hellojs;
```
```python
class HelloView(UnicornView):
    name = ""

    def say_hello_in_js(self):
        self.name = ""
        self.call('Hellojs.hello', self.name)
```

Thanks, @adamghill and all contributors!

**Comment by adamghill** [comment]
The code that handles that is pretty simple and looks at `window` for the passed-in method name: https://github.com/adamghill/django-unicorn/blob/bc72121/django_unicorn/static/js/component.js#L129. So, `this.window['Hellojs.hello']` won't work with the current code.

If you want to make a PR to handle "dotting-in" to an object, that would be great. Otherwise, I'll take a look at adding it in the next release or so!

**Comment by adamghill** [comment]
https://github.com/adamghill/django-unicorn/pull/174 looks pretty good, so I'll merge it into master and this feature will be in the next release.

**Comment by adamghill** [comment]
Closing this since the PR is now merged into master.

**Comment by nielsonsantana** [comment]
Thanks @adamghill, I tried this PR, but I didn't have enough time. I hope contribute more soon. 
This PR will help a lot.

**Comment by adamghill** [comment]
https://www.django-unicorn.com/docs/changelog/#v0-25-0 has been released with this fix! 🎉
