### ISSUE TITLE
Include this as a reference to reactor in the docs?

### ISSUE THREAD

**Issue by andrewtmendoza** [adamghill/django-unicorn#185]
Seems like an endorsement from the author of django-reactor!

https://www.reddit.com/r/django/comments/m8fa54/django_reactor/grh706h/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by adamghill** [comment]
When I reference similar projects in the documentation I try to be as objective as possible because they all approach the use case differently. I'm not sure one is "better" than another and I like that there are lots of different approaches.

I do appreciate the comment by Eddy, though! It was a very nice thing for him to say. :)
