### ISSUE TITLE
I can't seem to make things move

### ISSUE THREAD

**Issue by ben-kpa** [adamghill/django-unicorn#201]
I have followed the screencast. I have followed the tutorials. I have tried the example. Everything always seems about to work but it's just static. No "live updates" are happening to the counters, the todo app, or any other component I've tried. I tried installing everything with poetry as well. For some reason, nothing seems to "move". With the dev tools, I don't see any network requests for whatever component I try to use. I also get the errors below. It looks like they have something to do with my issue.

Firefox browser:
Loading module from “http://127.0.0.1:8000/static/js/unicorn.js” was blocked because of a disallowed MIME type (“text/plain”).
Loading failed for the module with source “http://127.0.0.1:8000/static/js/unicorn.js”.
Unicorn is missing. Do you need {% load unicorn %} or {% unicorn-scripts %}?

Chrome browser:
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
Unicorn is missing. Do you need {% load unicorn %} or {% unicorn-scripts %}?

FYI: {% load unicorn %} and {% unicorn-scripts %} have been included in all my tries.

Any help is highly appreciated!

**Comment by adamghill** [comment]
Hey! Sorry you are running into problems. Do you a sample repo I can look at to see if I can replicate the problem?

________________________________
From: ben-kpa ***@***.***>
Sent: Saturday, May 22, 2021 10:47:12 AM
To: adamghill/django-unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adamghill/django-unicorn] I can't seem to make things move (#201)


I have followed the screencast. I have followed the tutorials. I have tried the example. Everything always seems about to work but it's just static. No "live updates" are happening to the counters, the todo app, or any other component I've tried. I tried installing everything with poetry as well. For some reason, nothing seems to "move". With the dev tools, I don't see any network requests for whatever component I try to use. I also get the errors below. It looks like they have something to do with my issue.

Firefox browser:
Loading module from “http://127.0.0.1:8000/static/js/unicorn.js”<http://127.0.0.1:8000/static/js/unicorn.js%E2%80%9D> was blocked because of a disallowed MIME type (“text/plain”).
Loading failed for the module with source “http://127.0.0.1:8000/static/js/unicorn.js”<http://127.0.0.1:8000/static/js/unicorn.js%E2%80%9D>.
Unicorn is missing. Do you need {% load unicorn %} or {% unicorn-scripts %}?

Chrome browser:
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
Unicorn is missing. Do you need {% load unicorn %} or {% unicorn-scripts %}?

FYI: {% load unicorn %} and {% unicorn-scripts %} have been included in all my tries.

Any help is highly appreciated!

**Comment by adamghill** [comment]
Here is a screenshot of the developer toolbar in my example and it looks like like the JavaScript is loaded with `application/javascript` for the mimetype.

![CleanShot 2021-05-22 at 17 14 00](https://user-images.githubusercontent.com/317045/119241016-a74ba700-bb21-11eb-806d-3f3206c40272.png)

Maybe it's related to your version of Python or Django? Let me know what versions you are running as well if possible. Thanks!

**Comment by ben-kpa** [comment]
Here is an example repo. https://github.com/ben-kpa/temp-repo-dj-unicorn

![image](https://user-images.githubusercontent.com/31708278/119354739-173a6880-bcad-11eb-8658-b5d6b883e622.png)

the "learn more" link in the screenshot takes me to this link: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

Thank you for taking the time to look into this. I might be doing something wrong with the configurations that might be obvious to someone else but I didn't find anything when I googled so I was running out of options.

**Comment by adamghill** [comment]
I grabbed your repo above and everything seems to work on my OSX system. However, based on your screenshot it appears you are using Windows? I _think_ what is happening is described in this blog post: https://www.taricorp.net/2020/windows-mime-pitfalls/. They suggest updating your registry, however that doesn't seem reasonable to ask every user who installs `django-unicorn`! Another approach is to explicitly set the mimetype for ES6 modules: https://stackoverflow.com/a/16355034. An example commit for this is https://github.com/adamghill/temp-repo-dj-unicorn/commit/d82c38886de20d75534f1e8d54c1df9588a613e6.

I think setting the `MINIFIED` setting to `True` would also work. An example commit for this is https://github.com/adamghill/temp-repo-dj-unicorn/commit/4b3d7a6d8bd55381b269d3ac37dd6bb4662d3204.

If you could try both solutions (I don't have easy access to a Windows machine to test it out) and let me know if either (or both) fix the problem, I can add some documentation to help others who might hit the same issue. Thanks!

**Comment by ben-kpa** [comment]
I tried the one solution where I don't have to mess with my registry and it works!

Just adding these lines below in the settings.py, like in your fork, did the trick:
```
UNICORN = {
    "MINIFIED": True,
}

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
```

I tried the same with your repo with the "examples/", where I just added `"MINIFIED": True, ` in the existing UNICORN dictionary of the settings.py

So in the end it looked like this:
```
UNICORN = {"SERIAL": {"ENABLED": True, "TIMEOUT": 5,},
           "CACHE_ALIAS": "default",
            "MINIFIED": True
           }

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
```
At last, everything started behaving as it should.

Thank you for this great solution!

**Comment by adamghill** [comment]
That's awesome! If it's possible, can you test with each of those commented out?

For example, try this:
```python
#UNICORN = {
#    "MINIFIED": True,
#}

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
```

and:

```
UNICORN = {
    "MINIFIED": True,
}

#if DEBUG:
#    import mimetypes
#    mimetypes.add_type("application/javascript", ".js", True)
```

I'm trying to figure out if one or the other work or if they both would work so I can update the docs with the correct solution.

Thanks!

**Comment by ben-kpa** [comment]
This **works**:
```
# UNICORN = {
#     "MINIFIED": True,
# }

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
```

This doesn't work
```
UNICORN = {
    "MINIFIED": True,
}

# if DEBUG:
#     import mimetypes
#     mimetypes.add_type("application/javascript", ".js", True)

```

So I guess this here is the important part!
```
if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
```

**Comment by adamghill** [comment]
Awesome, thank you so much for the added information! 🎉

**Comment by ben-kpa** [comment]
It has been my pleasure! Looking forward to your Django con talk!
