### ISSUE TITLE
Extra examples (upvote and chat)

### ISSUE THREAD

**Issue by volkandkaya** [adamghill/django-unicorn#21]
Not sure if it is possible yet but the ability to upvote on multiple tabs/browsers and chat.

**Comment by adamghill** [comment]
Hey @volkandkaya, thanks for the suggestion. Having the ability to sync changes across different tabs/browsers is probably out of scope for this project without AJAX polling. However, you might want to look into https://github.com/edelvalle/reactor since websockets are the normal way to implement that sort of functionality.

Closing for now, but re-open if a polling example might be useful in the future.
