### ISSUE TITLE
Suggestion: `unicorn:` shorthand in templates

### ISSUE THREAD

**Issue by axwalker** [adamghill/django-unicorn#219]
Would it be possible to have a shorthand for `unicorn:` in component templates? Similar to the [v-bind shorthand](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand) in Vue. For example, this:

```html
<button unicorn:click="$reset">Reset the component</button>
```

Would become:

```html
<button :click="$reset">Reset the component</button>
```

It could be configurable even, so someone might just want to use `u:`:

```html
<button u:click="$reset">Reset the component</button>
```

---

I'm currently managing a large Django/Vue (with Nuxt) SPA and I'm trying to imagine what I would want to be able bring the unicorn dev experience a bit closer to the frontend dev experience I have with Nuxt. So I may soon come to you with lots of ideas beyond this initial minor one!

**Comment by adamghill** [comment]
It's not well documented, but the shorthand `u:` is already supported instead of `unicorn:` for all events and actions. I do think having it be `unicorn:` or `u:` makes it more explicit what framework is binding that element and prevents colliding with any other frameworks.

I ended up using `unicorn:` in all documentation to make it explicit, but I need to find a good place to make a note of the shorthand.

Let me know if you have other feature requests. I'm sure there are features to add to `Unicorn` that would be useful for others!

**Comment by axwalker** [comment]
Ah great, `u:` feels good enough to me!

**Comment by adamghill** [comment]
Made a note in the documentation in https://github.com/adamghill/django-unicorn.com/commit/a0a6d44a66f3adcdd43546f38c777d7947409d09 which is getting deployed live right now.
