### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by lorddaedra** [adamghill/django-unicorn#237]
```
eventListeners.js:116 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at HTMLDocument.<anonymous> (eventListeners.js:116)
(anonymous) @ eventListeners.js:116

```

```
      component.actionEvents[eventType].forEach((actionEvent) => {
```

I tried to use ```unicorn:click.discard="cancel"``` in child component.

**Comment by adamghill** [comment]
I do something similar in https://github.com/adamghill/django-unicorn/blob/master/example/unicorn/templates/unicorn/nested/row.html#L28. Can you replicate the error with my example or otherwise push an example to another repo so I can see what is going on? Thanks.

**Comment by clangley** [comment]
Hello, I've recently ran into this issue and created a simple project to reproduce this:
https://github.com/clangley/unicorn-typerror-example

* I have 2 components, list_todos and edit_todos.
* list_todos iterates over a handful of todos and renders a component for each.
* You can edit the todos on the page and when you hit save it will save to the database.
* After editing the first todo, it works and save correctly, any edits after will throw errors in console.

I have a small patch that will at least prevent throwing errors but it just checks for existence of eventType in component.actionEvents before doing the foreach. This appears to just work and solve the problem at the surface but not familiar enough with the code base to know if this is the correct fix or if it should be done elsewhere. 

Happy to spend some time looking into this more because I am currently accessing Django Unicorn for an upcoming project.

**Comment by adamghill** [comment]
@clangley Thank you so much for the example code and fix! I tested it out and it looks great. I'm merging it into `main` now. 👍
