### ISSUE TITLE
Updating class variables from outside

### ISSUE THREAD

**Issue by ashirvadz** [adamghill/django-unicorn#28]
HI Adam!

It would be useful to be able to update the unicorn component class variables from another Django app.
You mentioned an API call or database hookup on the page refresh.
How would this be done? 

Would this also be possible via AJAX or a Javascript hook?

Thanks!

Ashirvad

**Comment by ashirvadz** [comment]
Dear Adam,

Thank you for the suggestions. I will try to hit the database once the component is rendered and get the up-to-date amount. 

There will be some situations when the user's disk space gets updated without a page refresh. For example, when some uploaded files are deleted by the user, it's done via an AJAX call, and there's no refresh. 

Would there be a way to upload the component when watching the database's signals? DIskspace is a field in one of the models.

Thanks!

Ashirvad

**Comment by adamghill** [comment]
>upload the component when watching the database's signals
I can't think of a clean way to "push" data from the server-side to a component since it's pretty self-contained. All actions for `django-unicorn` _start_ from the frontend. However, it sounds like there is already a separate AJAX call to do the action, so I think my approach would be for `django-unicorn` to have a Javascript hook to be able to call methods on the component (similar to how the actions/`unicorn:click` works). So, inside of your AJAX call when you get a response back after the deleted a file, you could call something like `Unicorn.call('component-name', 'method_name', 'argument');`. This isn't currently possible, but seems doable.

If you _really_ want to push data from the server-side to the frontend, websockets seems like a better approach although it's a little more complicated to set the infrastructure up to support that. https://github.com/edelvalle/reactor is a nice library if you want to go down that road. `django-unicorn` is attempting to be a simple, drop-in solution for most problems, but is probably never going to support websockets or that complicated of a workflow.

**Comment by ashirvadz** [comment]
Hi Adam.

Thanks for the feedback. I took a good look at `reactor`, and it is way too complicated for a simple application like mine. I believe that `django-unicorn` would be perfect for it. 

If there could be a Javascript hook to call methods on the component, it would be perfect! This would solve my problem. I guess it would also benefit other users with a similar need.

Thank you!

Ashirvad

**Comment by adamghill** [comment]
>If there could be a Javascript hook to call methods on the component

Hopefully this should work for your purposes: https://github.com/adamghill/django-unicorn/commit/53fea2010576fd43814098f2ec0770b112d44b7b. It will be included in 0.5.0 which I should be able to get out in a day or two.

**Comment by ashirvadz** [comment]
Excellent! Thank you so much, Adam!

**Comment by adamghill** [comment]
Version 0.5.0 has now been released to pypi: https://pypi.org/project/django-unicorn/ with the addition of a `Unicorn.call` method. Documentation has also been updated: https://www.django-unicorn.com/documentation/components/actions#calling-methods.

Closing this for now, but feel free to open a new issue if this doesn't work for you!
