### ISSUE TITLE
Warn users if <div> is not wrapping component html

### ISSUE THREAD

**Issue by liamlawless35** [adamghill/django-unicorn#342]
I refactored some html code and broke my project due to the `<div>` tag not wrapping my html. Unicorn didn't throw any errors, nor did the browser. I was completely puzzled for ages. It could help other users down the line if this is implemented?

**Comment by adamghill** [comment]
This has happened to me before as well, so this would definitely be useful! It might be a little tricky because I use `BeautifulSoup` to parse the HTML in Python and it is very forgiving of invalid HTML (because usually that's what you want), but I might be able to figure out a way to provide more information to users.

**Comment by adamghill** [comment]
This was a little trickier than I expected, but I do have some code that prints a warning when a component's HTML doesn't _appear_ to be well formed in https://github.com/adamghill/django-unicorn/pull/351. I'm not sure if it should be on by default or if it will be noisy with false positives where the HTML would have been just fine.

Any thoughts on how aggressive Unicorn should be checking that component HTML looks valid?

**Comment by adamghill** [comment]
This will log a warning in the 0.42.0 release so I'm going to close this, but let me know what you think!
