### ISSUE TITLE
How to use UnicornView with mixin like LoginRequiredMixin

### ISSUE THREAD

**Issue by areski** [adamghill/django-unicorn#382]
I'm trying to figure out how to use a Mixin with UnicornView, e.g. to make sure the view is protected.

```
from django.contrib.auth.mixins import LoginRequiredMixin

class DynamicBarView(LoginRequiredMixin, UnicornView):
```
Unfortunately the above does not work. 
Any pointer on how to use a Mixin properly?
Thanks!

**Comment by adamghill** [comment]
Hello!

What are you trying to achieve with the `LoginRequiredMixin`? I could look into supporting it, but there seems to be some ambiguity what should happen. Would it be checked when the component `mounts` (i.e. when the component is first loaded), or only when an action occurs (i.e. when a method is called via ajax)? 

What I've tended to do is explicitly check as needed in my functions since then I have complete control.

```python
class DynamicBarView(UnicornView):
    def some_action(self):
        print("some_action called")

        if not self.request.user.is_authenticated:
            raise Exception("user is not authenticated")

        ...
```

But, if you have a suggestion for how `LoginRequiredMixin` should work, I'd love to hear it.

**Comment by areski** [comment]
As `UnicornView` inherits from `TemplateView`, I expected the normal Mixins to work, I understand that this is not the case now, so glad that I was not doing something wrong.

I would expected it to be called for every ajax calls, so everytime an action occurs. For instance in my test project I have a progress bar and if the user log out on an other tab, I don't want the progress bar to keep working as the user session is finished, I imagine other users might have similar scenarios.

Your solution definitely work for me in the meantime. Thanks for that @adamghill! Great project btw :D

**Comment by adamghill** [comment]
Ah, that makes sense. I'll think more about whether supporting `LoginRequiredMixin` might work. One other approach I wanted to mention was you could use the [login required decorator](https://docs.djangoproject.com/en/stable/topics/auth/default/#the-login-required-decorator) on an action method -- that should work as well!

I'm going to close this for now, but I might re-open in the future.
