### ISSUE TITLE
generated js code location

### ISSUE THREAD

**Issue by jacopsd** [adamghill/django-unicorn#386]
When using several components on 1 page, the generated js code is placed in between the components. This causes issue e.g. in combination with masonry (see https://masonry.desandro.com) where content in between components disturbs the page layout.

Suggestion is to add an option where the generated js code can be placed at the bottom of the generated HTML, typically in a custom-js block OR (maybe easier) within the template root element surrounding the component template, and not below that root element.

**Comment by adamghill** [comment]
Interesting! Yeah, I can see how that might cause some issues.  I made a quick PR to just test out how this might work with https://github.com/adamghill/django-unicorn/pull/387. I think I might put this behind a setting because I'm a little worried it is going to break something I haven't tested, yet. But, it does _seem_ to work with some simple tests I've done so far. I'll let you know how the rest of my testing goes!
