### ISSUE TITLE
Nested components with more than one ancestor

### ISSUE THREAD

**Issue by dvdmgl** [adamghill/django-unicorn#400]
Having
```python
class GrandParentView(UnicornView):
   pass
class ParentView(UnicornView):
   pass
class ChildView(UnicornView):
   pass
```

`grand_parent.html`
```html
        {% for parent in parents %}
            {% unicorn 'parent' parent=view id=parent.id parent=parent %}
        {% endfor %}
```
`parent.html`
```html
        {% for child in childs %}
            {% unicorn 'child' parent=view id=child.id child=child %}
        {% endfor %}
```

`parent=view` refers to the root view, in this case `GrandParentView`, how to specify that in `parent.html` that the parent view is `ParentView` and not `GrandParentView` the root view.

**Comment by adamghill** [comment]
I've never tried multiple nested layers and I have a sneaking suspicion that other parts of `Unicorn` would break (see https://github.com/adamghill/django-unicorn/blob/3184b00/django_unicorn/components/unicorn_view.py#L361 for one potential place).

I'm going to close this for now because I won't add this functionality any time soon, but if you make a PR for this feature I would take a look at it. 👍
