### ISSUE TITLE
Using websockets for better perf

### ISSUE THREAD

**Issue by ociule** [adamghill/django-unicorn#478]
Hi there,

Thanks for the great work on unicorn.

Is there interest to add websocket support in a future version for better performance ? I experimented with tetris clones in both websocket (reactor) and AJAX request libraries (unicorn, htmx) and there is a performance difference.

If you think the performance difference doesn't come from websockets, I'd be glad for any tips to delivering a more fluid UI

Cheers,

**Comment by adamghill** [comment]
Pretty sure there would be a performance improvement using websockets if only because of network latency. I mention this in [this post](https://dev.to/adamghill/lessons-learned-building-a-fullstack-framework-for-django-2cml), but the original idea _was_ to use websockets for `Unicorn`. However, I wanted a simple deployment story which didn't require much changes to an existing "regular" Django app. It is also my belief that for a majority of websites AJAX is "good enough", especially with judicious use of `partial` updates to keep the payloads as small as possible.

However, for building a game I would think websockets would be a better choice. It sounds like you already tried out `reactor`, but most of the Python/Django full-stack libraries use websockets -- [here is a list](https://www.django-unicorn.com/docs/#full-stack-framework-python-packages) of some others in case that's helpful.

If someone built a new transport layer for `Unicorn` that used websockets I would take a look at it, but it's not something I would build myself since 1) it doesn't fit any use case I currently have, 2) it would add complexity to the code, and 3) it would increase the amount of support and testing I would need to do for every new feature.

I'm going to close this for now, but feel free to re-open this issue if you are interested in making a PR with websocket support. 👍 

P.S. I would _love_ to see a tetris clone in `Unicorn` if you are able to make a public repo and share it. It would be a pretty fun test case -- I'm sure there are performance optimizations that could be made to `Unicorn` even if the only transport model is AJAX.

**Comment by ociule** [comment]
@adamghill Here's the tetris implementation I used: https://github.com/ociule/django_htmx_unicorn

Hope it helps, cheers
