### ISSUE TITLE
Child component loses a reference to its parent on server restart 

### ISSUE THREAD

**Issue by imankulov** [adamghill/django-unicorn#593]
When the server restarts, self.parent is resolved to None. A full page reload is necessary to restore the connection.

## Sample setup

There are two components: a wrapper with a counter and a button that updates the counter (the same as in #592)

- Wrapper Python: [link](https://github.com/imankulov/django-unicorn-demo/blob/main/django_unicorn_bug/components/wrapper.py)
- Wrapper HTML: [link](https://github.com/imankulov/django-unicorn-demo/blob/main/django_unicorn_bug/templates/unicorn/wrapper.html)
- Button Python: [link](https://github.com/imankulov/django-unicorn-demo/blob/main/django_unicorn_bug/components/button.py)
- Button HTML: [link](https://github.com/imankulov/django-unicorn-demo/blob/main/django_unicorn_bug/templates/unicorn/button.html)

## More information

- Demo repository: [link](https://github.com/imankulov/django-unicorn-demo)
- Video demonstrating the issue: [link](https://www.loom.com/share/77770e5a65394900903dfe2126c1ffe0)

**Comment by adamghill** [comment]
This is happening because instantiated components get cached to prevent having to re-create them on every request. However, the default Django cache is local memory so when the server goes away, so does the cache. Any persistent cache will prevent this issue from happening -- I tend to use `redis` for my production apps, but even the filesystem would work for testing purposes:

```python
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/var/tmp/django_cache",
    }
}
```

I will add a note to the documentation about this requiring a persistent cache.

I do have a hunch about a different approach that would fix this even with the local memory cache, but I'm still working on it.

**Comment by imankulov** [comment]
Thank you for your response. I can confirm that having a persistent cache solves the issue. I agree that explicitly outlining the role of the cache in the system would be very helpful. Other than this, I think the issue can be closed, as it's not a bug, but rather "working as intended" in the current architecture.

**Comment by adamghill** [comment]
Sounds good! I will close this for now, but will tag it when I update the documentation.
